name: Push to Main Discord Notification

on:
    push:
        branches:
            - main
        # paths:
        #   - 'repo1/**'
        #   - 'repo2/**'

jobs:
    send-notification:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Send Discord Notification
              uses: appleboy/discord-action@master
              with:
                  webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  content: "A push has been made to the main branch of this repository."
