name: discord message
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: send custom message with args
              uses: appleboy/discord-action@master
              with:
                  webhook_id: ${{ secrets.WEBHOOK_ID }}
                  webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                  args: ${{ github.event_name }} event triggered first step.
                  #   https://discord.com/api/webhooks/1168836836148392086/7tNgvwa2PTV6XCVhApINjP88CPGL-RhRReq0ORm0ngCQU3w6s1OBluWFq_em4v0ubad_

                  #   7tNgvwa2PTV6XCVhApINjP88CPGL-RhRReq0ORm0ngCQU3w6s1OBluWFq_em4v0ubad_
